### ISSUE TITLE
Would prefer to use toxenv names in strategy matrix

### ISSUE THREAD

**Issue by merwok** [tox-dev/tox-gh#8]
Hello!  With other CI providers, I like to define one CI check/job per tox environment, for example one for each of py38, py39, py310-coverage, lint.  For github actions, I understand that it’s easy to use python version as an axis, so that the values generate combinations and can be used as parameter for the python install action.  But having to run multiple jobs (e.g. py310 and lint / type check / doc check/etc) in one check feels backward to me: it’s driven by what the tool can do rather than what I want to see.
It doesn’t make sense to have one check that runs tests with latest python and lint, these should be separate jobs with separate success status.

Inspired by a comment somewhere, I ditched tox-gh-actions, used tox-env as matrix axis and used an external config file to map tox-env value to python install parameter: https://github.com/caravancoop/configstore/blob/main/.github/workflows/configstore.yml#L11
(I tried to configure all in the yaml file at first with complicated expressions but that was not worth it)

It would be great to have native support for this!

I don’t really have implementation suggestion.  If we can add arbitrary config in the actions config file, maybe a mapping could be defined there?  If not, it might have to be a job with outputs and that could be heavy (if it needs to call tox or use a shell).

```yaml
jobs:
  test:
    name: test ${{ matrix.tox-env }}
    strategy:
      fail-fast: false
      matrix:
        tox-env:
          - "3.10"
          - "3.9"
          - "3.8"
          - "lint"
          - "pkg"

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ some-expression-to-get-version }}
```
